progress on restore function

diff --git a/cluster b/cluster
--- a/cluster
+++ b/cluster
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+trap 'handle_error $LINENO' ERR
+
 # A simple script to help with cluster management
 #
 #   cluster status        - what's the status of the cluster (default)
@@ -38,7 +40,7 @@ DOCKER="sudo docker"
 # 1. Untar the backup file (into tmp?)
 # 2. For each tgz file in the backup:
 #   2.1 Confirm a matching entry in the compose file
-#   2.2 Confirm a matching entry in container engine - note parent context of restore (ability to re-home)
+#   2.2 ? Confirm a matching entry in container engine - note parent context of restore (ability to re-home)
 #   2.3 Run a simple container, mounting the volume and the backup
 #   2.4 Import the backup into the volume with tar on the specific volume
 # 3. Cleanup the backup dir (leaving the backup.tgz untouched)
@@ -57,7 +59,7 @@ cmd_export() {
     if ! $DOCKER volume inspect --format '{{.Name}}' "$VOLUME_NAME";
     then
         echo "Error: Volume $VOLUME_NAME does not exist"
-        exit 1
+        #FIXME exit 1
     fi
 
 # TODO: if FILE_NAME starts with / we need to error out
@@ -66,29 +68,63 @@ cmd_export() {
 # Added redirect to dev/null. remove to debug
 
     if ! $DOCKER run --rm \
-      -v "$VOLUME_NAME":/vackup-volume \
-      -v "$(pwd)":/vackup \
+      -v "$VOLUME_NAME":/backup-volume \
+      -v "$(pwd)":/backup \
       busybox \
-      tar -zcvf /vackup/"$FILE_NAME" /vackup-volume >/dev/null 2>&1 ;
+      tar -zcvf /backup/"$FILE_NAME" /backup-volume >/dev/null 2>&1 ;
     then
-        echo "Error: Failed to start busybox backup container"
-        exit 1
+        #echo "Error: Failed to start busybox backup container"
+        #exit 1
+        #FIXME after testing
+        touch $FILE_NAME
     fi
 
     echo "Successfully tar'ed volume $VOLUME_NAME into file $FILE_NAME"
 }
 
+cmd_import() {
+    FILE_NAME="$1"
+    VOLUME_NAME="$2"
+    
+    if [ -z "$VOLUME_NAME" ] || [ -z "$FILE_NAME" ]; then
+        echo "Error: Not enough arguments"
+        usage
+        exit 1
+    fi
+    
+    if ! $DOCKER volume inspect --format '{{.Name}}' "$VOLUME_NAME";
+    then
+        echo "Error: Volume $VOLUME_NAME does not exist"
+        $DOCKER volume create "$VOLUME_NAME"
+    fi
+
+# TODO: check if file exists on host, if it does
+# create a option for overwrite and check if that's set
+# TODO: if FILE_NAME starts with / we need to error out
+# unless we can translate full file paths    
+
+    if ! $DOCKER run --rm \
+      -v "$VOLUME_NAME":/backup-volume \
+      -v "$(pwd)":/backup \
+      busybox \
+      tar -xvzf /backup/"$FILE_NAME" -C /; 
+    then
+        echo "Error: Failed to start busybox container"
+        #exit 1
+    fi
+    echo imported $VOLUME_NAME, from $FILE_NAME
+}
 
 cmd_backup() {
 	# get the context from parent dir
 	# NOTE:glossary - "context" is the namespace derived from the parent directory that compose uses in the docker engine.
 	dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
 	context="$(basename $dir)"
-	echo context=$context
+	#echo context=$context
 	
 	datestr="$(date +%Y%m%H%M)"
 	backupdir="$context-$datestr"
-	mkdir -p backupdir
+	mkdir -p $backupdir
 	
 	# parse the composefile to get the volume names
 	yq e '.volumes | keys | .[]' $composefile | while read volume ; do
@@ -96,12 +132,32 @@ cmd_backup() {
 		target="${backupdir}/${volume}.tgz"
 		cmd_export $volname $target
 		#echo export $volname $target
-	done	
+	done
+
+    # finally, tar the tarfiles
+    tar -zcvf "$backupdir".tgz $backupdir
 }
 
 cmd_restore() {
 	tarfile=$1
-	echo "RESTORE $tarfile (todo)"
+    dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
+	context="$(basename $dir)"
+
+    # untar the tar to a new TMP_DIR
+    #TMP_DIR=`mktemp -d` && tar -C $TMP_DIR -xf $tarfile
+    tar -xf $tarfile
+    tardir=${tarfile%.*}
+    #echo Restored backup to tmp: $TMP_DIR/$tarname
+
+    # parse the composefile to get the volume names
+	yq e '.volumes | keys | .[]' $composefile | while read volume ; do
+		volname="${context}_$volume"		
+		target="$tardir/$volume.tgz"
+        cmd_import $target $volname
+        #echo restored $volname, from $tarfile
+	done
+    rm -fr $tardir
+    echo restored $context from $tarfile
 }
 
 # note: resolve $0 to get full path, and cd to it.
